/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthGroupsGroupIdIndexRouteImport } from './routes/_auth.groups.$groupId.index'
import { Route as AuthGroupsGroupIdTopicsTopicIdRouteImport } from './routes/_auth.groups.$groupId.topics.$topicId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsGroupIdIndexRoute = AuthGroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsGroupIdTopicsTopicIdRoute =
  AuthGroupsGroupIdTopicsTopicIdRouteImport.update({
    id: '/groups/$groupId/topics/$topicId',
    path: '/groups/$groupId/topics/$topicId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/groups/$groupId': typeof AuthGroupsGroupIdIndexRoute
  '/groups/$groupId/topics/$topicId': typeof AuthGroupsGroupIdTopicsTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/groups/$groupId': typeof AuthGroupsGroupIdIndexRoute
  '/groups/$groupId/topics/$topicId': typeof AuthGroupsGroupIdTopicsTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/_auth/groups/$groupId/': typeof AuthGroupsGroupIdIndexRoute
  '/_auth/groups/$groupId/topics/$topicId': typeof AuthGroupsGroupIdTopicsTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/auth/callback'
    | '/join/$code'
    | '/groups/$groupId'
    | '/groups/$groupId/topics/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/dashboard'
    | '/auth/callback'
    | '/join/$code'
    | '/groups/$groupId'
    | '/groups/$groupId/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/_auth/dashboard'
    | '/auth/callback'
    | '/join/$code'
    | '/_auth/groups/$groupId/'
    | '/_auth/groups/$groupId/topics/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$groupId/': {
      id: '/_auth/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$groupId/topics/$topicId': {
      id: '/_auth/groups/$groupId/topics/$topicId'
      path: '/groups/$groupId/topics/$topicId'
      fullPath: '/groups/$groupId/topics/$topicId'
      preLoaderRoute: typeof AuthGroupsGroupIdTopicsTopicIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGroupsGroupIdIndexRoute: typeof AuthGroupsGroupIdIndexRoute
  AuthGroupsGroupIdTopicsTopicIdRoute: typeof AuthGroupsGroupIdTopicsTopicIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGroupsGroupIdIndexRoute: AuthGroupsGroupIdIndexRoute,
  AuthGroupsGroupIdTopicsTopicIdRoute: AuthGroupsGroupIdTopicsTopicIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
